### ISSUE TITLE
npm link kredits-contracts fails 

### ISSUE THREAD

**Issue by bumi** [67P/kredits-web#81]
For local development I try to link the local `kredits-contracts` npm package. 

after running `npm link kredits-contracts` starting the ember app fails with: `Couldn't find preset "es2015" relative to directory "/home/bumi/src/kredits/truffle-kredits/lib/utils" while parsing file: /home/bumi/src/kredits/truffle-kredits/lib/utils/preflight.js` 
 
Here is the complete log: 

```
kredits/kredits-web@master  » npm --version
5.6.0
kredits/kredits-web@master  » node --version
v8.11.3
kredits/kredits-web@master  » rm -rf node_modules 
kredits/kredits-web@master  » npm install
[...]
added 2375 packages in 39.877s
npm start  # works!
Build successful (37679ms) – Serving on http://localhost:4200/

# now linking kredits-contracts

npm link kredits-contracts
/home/bumi/src/kredits/kredits-web/node_modules/kredits-contracts -> /home/bumi/.node_modules/lib/node_modules/kredits-contracts -> /home/bumi/src/kredits/truffle-kredits

kredits/kredits-web@master  » npm start

> kredits-web@1.0.0 start /home/bumi/src/kredits/kredits-web
> ember serve

Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
Build Error (CoreObject)

Couldn't find preset "es2015" relative to directory "/home/bumi/src/kredits/truffle-kredits/lib/utils" while parsing file: /home/bumi/src/kredits/truffle-kredits/lib/utils/preflight.js


Stack Trace and Error Report: /tmp/error.dump.d7a4d0f775a20c7aefb4990be84e74fd.log

tail -n 100 /tmp/error.dump.d7a4d0f775a20c7aefb4990be84e74fd.log
[...]

ERROR Summary:

  - broccoliBuilderErrorStack: Error: Couldn't find preset "es2015" relative to directory "/home/bumi/src/kredits/truffle-kredits/lib/utils" while parsing file: /home/bumi/src/kredits/truffle-kredits/lib/utils/preflight.js
    at /home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Babelify._flush (/home/bumi/src/kredits/kredits-web/node_modules/babelify/index.js:27:24)
  - codeFrame: Couldn't find preset "es2015" relative to directory "/home/bumi/src/kredits/truffle-kredits/lib/utils" while parsing file: /home/bumi/src/kredits/truffle-kredits/lib/utils/preflight.js
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `CoreObject` plugin. 💥
Couldn't find preset "es2015" relative to directory "/home/bumi/src/kredits/truffle-kredits/lib/utils" while parsing file: /home/bumi/src/kredits/truffle-kredits/lib/utils/preflight.js
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `CoreObject` plugin. 💥
Couldn't find preset "es2015" relative to directory "/home/bumi/src/kredits/truffle-kredits/lib/utils" while parsing file: /home/bumi/src/kredits/truffle-kredits/lib/utils/preflight.js
  - name: Error
  - nodeAnnotation: ember-browserify
  - nodeName: CoreObject
  - originalErrorMessage: Couldn't find preset "es2015" relative to directory "/home/bumi/src/kredits/truffle-kredits/lib/utils" while parsing file: /home/bumi/src/kredits/truffle-kredits/lib/utils/preflight.js
  - stack: Error: Couldn't find preset "es2015" relative to directory "/home/bumi/src/kredits/truffle-kredits/lib/utils" while parsing file: /home/bumi/src/kredits/truffle-kredits/lib/utils/preflight.js
    at /home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/bumi/src/kredits/kredits-web/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Babelify._flush (/home/bumi/src/kredits/kredits-web/node_modules/babelify/index.js:27:24)
```

**Comment by bumi** [comment]
ref #80

**Comment by skddc** [comment]
I get a different error now. Looks like something about the module export in `kosmos-schemas` is tripping up the Ember build pipeline...

**Comment by raucao** [comment]
Finally resolved properly.
